### ISSUE TITLE
after setup, problems reading folders.

### ISSUE THREAD

**Issue by bradholland** [stoerr/CoDeveloperGPTengine#47]
Hi There, 
Firstly, thanks for your wonderful tool. very exciting!

I worked through your setup process (actually had chatgpt guide me through it)
everything seems to be working, I set up tunneling via serveo and created my api keys etc. 
I am chatting with the engine via my custom gpt, but I cannot seem to get it to see or list folders. 
i had it create a helloworld.txt file in the root folder it has access to, so i know it's working in that respect. 
for example, in the image below, all it can tell me it sees as the two makefiles and readme. 
I can tell it to look in a folder if i give it the name of the folder, but if I ask it what folders it sees, it falls over. 
Any ideas?
<img width="546" alt="image" src="https://github.com/user-attachments/assets/b8b34e00-b73a-41b5-be34-4e918feebe42">

**Comment by stoerr** [comment]
Hi!
Great to hear that you give it a try! Well, that can have several causes. The local server does output debugging messages, such as the actions it does. What does it print when you try that? It does log the actions it executes. Does it log just the writing action, but not the reading action, or does it log both? If it doesn't log the reading action, then there is likely something off with the GPT you created; if it does log the reading action but that just doesn't return something, then there is some problem with the local server.
Best regards,
Hans-Peter

**Comment by stoerr** [comment]
Well, if you still have problems with this, I guess the easiest way would be to have a video call with screen sharing to resolve it. Please contact me if you'd like this - unfortunately I need more information to see what the actual problem is. So I'm closing the ticket for now, but please feel free to contact me or open it again if you want the problem solved. Thanks for trying it!
